---
- name: Update apt package
  apt:  name="*" state=latest update_cache=true force_apt_get=true 

- name: Install Java 11
  apt: name=default-jdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.67/bin/apache-tomcat-9.0.67.tar.gz  dest=/opt/apache-tomcat-9.0.67.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-9.0.67.tar.gz -C /opt/ creates=/opt/apache-tomcat-9.0.67

- name: Symlink install directory
  file: src=/opt/apache-tomcat-9.0.67 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/systemd/system/tomcat.service mode=0755

- name: Start Tomcat
  systemd: name=tomcat state=started

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: wait for tomcat to start
  wait_for: port=8080
